### PR TITLE
fix: Add contracts to LIC4 Tests (Closes #138)

### LINKED ISSUE #138: fix: Add contract to LIC 4 tests
Add descriptive comments above each test noting their intended purpose.

### PR DESCRIPTION
**Pull request by Laafayeette**
Contains the contracts, i.e., method comments explaining each test for each test of LIC 4.

### CODE REVIEW

**Comment by KevinLov** [comment]
LGTM

File: src/test/java/se/kth/DD2480/CMVTest.java [hunk 1]
```diff
@@ -358,41 +373,56 @@ void lic4_ReturnsFalseWhenSetIsClearedWhenItWouldHaveReturnedTrueOtherwise() {
...
+     */
     @Test
     void lic4_ReturnsTrueWhenTwoConsecutiveSpreadInTwoDistinctQuads() {
         CMV cmv = new CMV();
         Point[] points = {new Point(0, 0), new Point(-1, -1)};
         assertTrue(cmv.lic4(points, points.length, 2, 1));
     }
 
+    /**
+     * With Q_PTS = 2 and QUADS = 1 lic4 will return true iff there exists two consecutive points that cover more than
```
Comment (Eggetxd) [inline src/test/java/se/kth/DD2480/CMVTest.java]: This test has Q_PTS = 3 and QUADS = 2
